version: '3.5'
services:
  php:
    image: yiisoftware/yii2-php:7.4-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app:delegated
    ports:
      - '80:80'
    networks:
      backend:
        aliases:
          - app

  test-app-mysql-db:
    image: mysql:5.7
    container_name: test-app-mysql-db
    ports:
      - '33061:3306'
    volumes:
      - ./runtime/var:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=securerootpassword
      - MYSQL_DATABASE=testapp
      - MYSQL_USER=testapp
      - MYSQL_PASSWORD=testapp
    networks:
      backend:
        aliases:
          - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - test-app-mysql-db:db
    ports:
      - '8765:80'
    environment:
      MYSQL_ROOT_PASSWORD: securerootpassword
      PMA_HOST: db
    depends_on:
      - test-app-mysql-db
    networks:
      backend:
        aliases:
          - pma

networks:
  backend:
    name: backend-network